### ISSUE TITLE
Перестал клюкать

### ISSUE THREAD

**Issue by GoldVital** [Cybertat1on/Qlyuker#8]
Что то обновили, перестал клюкать.
Отключил клюки, вроде бы собирает часовые и бусты качает

**Comment by pharaoh347** [comment]
![image](https://github.com/user-attachments/assets/7fe11698-3d5d-4913-92de-ddf1f808024b)
Так же обновили дейлик.

**Comment by gInnaro** [comment]
откройте папку bot, затем core, а затем откройте файл headers.py, и там добавьте строку 
'Klyuk': '0110101101101100011011110110111101101011',

чтобы вышло вот так
![ow6HeHD5QQ](https://github.com/user-attachments/assets/59097276-c7bf-494e-b734-d499d94e7840)

и все заработает

**Comment by GoldVital** [comment]
Решено
